# Generated by Django 4.2.2 on 2023-07-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ballena',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tiburon',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
