# Generated by Django 4.2.2 on 2023-07-17 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0003_animal_descripcion_ballena_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiburon',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/static/assets'),
        ),
        migrations.CreateModel(
            name='InicioInfoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inicio_infoextra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
