# Generated by Django 4.2.2 on 2023-07-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_tiburon_avatar_inicioinfoextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/static/assets'),
        ),
        migrations.AddField(
            model_name='ballena',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/static/assets'),
        ),
    ]
